server:
  port: 9091
  
spring:
  application:
    name: API-GATEWAY
  
  cloud: 
    gateway:
      routes:
      - id: USER-SERVICES
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/department/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
